// export const CONNECTIONS: [string, string][] = [
//   ['left_shoulder', 'right_shoulder'],
//   ['left_shoulder', 'left_elbow'],
//   ['left_elbow', 'left_wrist_pose'],
//   ['right_shoulder', 'right_elbow'],
//   ['right_elbow', 'right_wrist_pose'],
//   ['left_hip', 'right_hip'],
//   ['left_shoulder', 'left_hip'],
//   ['right_shoulder', 'right_hip'],
//   ['left_hip', 'left_knee'],
//   ['left_knee', 'left_ankle'],
//   ['left_ankle', 'left_heel'],
//   ['left_heel', 'left_foot_index'],
//   ['right_hip', 'right_knee'],
//   ['right_knee', 'right_ankle'],
//   ['right_ankle', 'right_heel'],
//   ['right_heel', 'right_foot_index'],
//   ['left_thumb_CMC', 'left_thumb_MCP'],
//   ['left_thumb_MCP', 'left_thumb_IP'],
//   ['left_thumb_IP', 'left_thumb_tip'],
//   ['left_wrist', 'left_thumb_CMC'],
//   ['left_index_finger_MCP', 'left_index_finger_PIP'],
//   ['left_index_finger_PIP', 'left_index_finger_DIP'],
//   ['left_index_finger_DIP', 'left_index_finger_tip'],
//   ['left_wrist', 'left_index_finger_MCP'],
//   ['left_middle_finger_MCP', 'left_middle_finger_PIP'],
//   ['left_middle_finger_PIP', 'left_middle_finger_DIP'],
//   ['left_middle_finger_DIP', 'left_middle_finger_tip'],
//   ['left_wrist', 'left_middle_finger_MCP'],
//   ['left_ring_finger_MCP', 'left_ring_finger_PIP'],
//   ['left_ring_finger_PIP', 'left_ring_finger_DIP'],
//   ['left_ring_finger_DIP', 'left_ring_finger_tip'],
//   ['left_wrist', 'left_ring_finger_MCP'],
//   ['left_pinky_MCP', 'left_pinky_PIP'],
//   ['left_pinky_PIP', 'left_pinky_DIP'],
//   ['left_pinky_DIP', 'left_pinky_tip'],
//   ['left_wrist', 'left_pinky_MCP'],
//   ['right_thumb_CMC', 'right_thumb_MCP'],
//   ['right_thumb_MCP', 'right_thumb_IP'],
//   ['right_thumb_IP', 'right_thumb_tip'],
//   ['right_wrist', 'right_thumb_CMC'],
//   ['right_index_finger_MCP', 'right_index_finger_PIP'],
//   ['right_index_finger_PIP', 'right_index_finger_DIP'],
//   ['right_index_finger_DIP', 'right_index_finger_tip'],
//   ['right_wrist', 'right_index_finger_MCP'],
//   ['right_middle_finger_MCP', 'right_middle_finger_PIP'],
//   ['right_middle_finger_PIP', 'right_middle_finger_DIP'],
//   ['right_middle_finger_DIP', 'right_middle_finger_tip'],
//   ['right_wrist', 'right_middle_finger_MCP'],
//   ['right_ring_finger_MCP', 'right_ring_finger_PIP'],
//   ['right_ring_finger_PIP', 'right_ring_finger_DIP'],
//   ['right_ring_finger_DIP', 'right_ring_finger_tip'],
//   ['right_wrist', 'right_ring_finger_MCP'],
//   ['right_pinky_MCP', 'right_pinky_PIP'],
//   ['right_pinky_PIP', 'right_pinky_DIP'],
//   ['right_pinky_DIP', 'right_pinky_tip'],
//   ['right_wrist', 'right_pinky_MCP'],
// ];

export const CONNECTIONS: Array<[number, number]> = [
  // [0,1],[1,2],[2,3],[3,7],
  // [0,4],[4,5],[5,6],[6,8],
  // [9,10],
  [11,12],[11,13],[13,15],
  [12,14],[14,16],
  [15,17],[17,19],[19,21],
  [16,18],[18,20],[20,22],
  // [11,23],[12,24],
  [23,24],[23,25],[24,26],
  [25,27],[27,31],[26,28],[28,32],
  [27,29],[29,31],[28,30],[30,32],
  [33,34], [34, 35],
  // [11,35], [12,35],[23,35], [24,35]
  [33, 0]
];
